export const STATUS = Object.freeze({
  PENDING: "PENDING",
  CONFIRMED: "CONFIRMED",
  CANCELLED: "CANCELLED",
  DELIVERED: "DELIVERED",
  RETURNED: "RETURNED",
  REFUNDED: "REFUNDED",
  FAILED: "FAILED",
});
